### ISSUE TITLE
Weird images

### ISSUE THREAD

**Issue by robertoachar** [hagnerd/gatsby-starter-blog-mdx#15]
Hi,

Do you know why images are being displayed this way?

Link: [https://gatsby-starter-blog-mdx-demo.netlify.com/hello-world](https://gatsby-starter-blog-mdx-demo.netlify.com/hello-world)

<img width="968" alt="Screen Shot 2019-09-08 at 10 44 37" src="https://user-images.githubusercontent.com/7755073/64489123-b5f70b00-d225-11e9-859c-73ba3537f472.png">

Thanks

**Comment by hagnerd** [comment]
Hm... I do not. I will have to look into this. It might be regression from the recent package upgrades that I did.

**Comment by robertoachar** [comment]
Hey, thanks for you reply.

I've found an issue on Gatsby. Maybe it's related.

https://github.com/gatsbyjs/gatsby/issues/15486

**Comment by hagnerd** [comment]
Awesome! Thanks. I'll start by digging in there first.

**Comment by robertoachar** [comment]
Hey,

I've found a workaround for it. I added `gatsby-remark-images` in `gatsbyRemarkPlugins` and `plugins` as well.

Hope it helps you.

See:
https://github.com/robertoachar/robertoachar.dev/blob/626f3c4b03831f8a6d9af9db7fb80a944a691ee1/gatsby-config.js#L57

**Comment by hagnerd** [comment]
Hey @robertoachar thanks for reporting. I'm sorry it took a while. I've been on a client project that uses a different Git client so unfortunately my personal Github account has been neglected for a while. 

This issue is fixed with #17. I'm going to close this issue, but if you see anything else, or it doesn't work the way you expected feel free to re-open.
